# src/main/resources/crd.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: websites.demo.example.com
spec:
  group: demo.example.com
  names:
    kind: Website
    plural: websites
    singular: website
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [ image ]
              properties:
                image: { type: string }
                replicas: { type: integer, minimum: 1, default: 1 }
                port: { type: integer, minimum: 1, maximum: 65535, default: 8080 }
            status:
              type: object
              properties:
                url: { type: string }
                phase: { type: string }
                message: { type: string }